### ISSUE TITLE
Practica 1

### ISSUE THREAD

**Issue by hiuta** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-hiuta#2]
[practica 1 Paulino joel.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-hiuta/files/6173384/practica.1.Paulino.joel.pdf)

**Comment by Itzelzun** [comment]
Calificacion 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
